### ISSUE TITLE
remoteerror exception when inviting people

### ISSUE THREAD

**Issue by moeinrahimi** [TechnitiumSoftware/BitChatClient#3]
hi i just installed your amazing software.
when i invite people after few seconds in chat area i get this two messages 

[3 Mar, 2017 14:41:17] Secure channel with peer '[10.42.0.1:46160]' encountered 'RemoteError' exception.

```
[3 Mar, 2017 14:42:25] BitChatCore.Network.SecureChannel.SecureChannelException: Remote client sent an error response code: UnknownException
   at BitChatCore.Network.SecureChannel.SecureChannelPacket..ctor(Stream s)
   at BitChatCore.Network.SecureChannel.SecureChannelClientStream.ProtocolV4(Stream stream)
   at BitChatCore.Network.SecureChannel.SecureChannelClientStream..ctor(Stream stream, IPEndPoint remotePeerEP, CertificateStore clientCredentials, Certificate[] trustedRootCertificates, ISecureChannelSecurityManager manager, SecureChannelCryptoOptionFlags supportedOptions, Int32 reNegotiateOnBytesSent, Int32 reNegotiateAfterSeconds, Byte[] preSharedKey)
```

**Comment by ShreyasZare** [comment]
Hi, thanks for the feedback. I will check for this issue and update here.

**Comment by ShreyasZare** [comment]
Hi, I have released a new update few days ago which should be fixing this unknown exception issue which may occur due to underlying network connection getting disconnected. I am closing this issue for now.
